version: '2'
services:
  db:
    image: postgres:17
    user: root
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  odoo18:
    container_name: ${INSTANCE_NAME}_odoo
    image: odoo:18
    user: root
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
      - "${ODOO_CHAT_PORT}:8072"
    volumes:
      - ./addons:/mnt/extra-addons
      - //Users/motaouakkel/Documents/shared_addons:/mnt/extra-addons/shared
      - ./etc:/etc/odoo
    environment:
      - HOST=${HOST}
      - USER=${DB_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PIP_BREAK_SYSTEM_PACKAGES=1
    restart: always